#  设置服务名
spring:
  application:
    name: client2Service
#  设置注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8090/eureka
server:
 port: 8199
#feign远程调用配置
feign:
  hystrix:
    #开启熔断
    enabled: true
# 熔断策略
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
#熔断监控仪表板查看地址  http://host:port/actuator/hystrix.stream
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

